# Generated by Django 4.1.3 on 2023-02-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("e_id", models.CharField(max_length=20)),
                ("e_name", models.CharField(max_length=20)),
                ("e_email", models.EmailField(max_length=254)),
                ("e_contact_no", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "employee",
            },
        ),
    ]
